//PIN
export const PIN_OPEN= 'PIN_OPEN';
export const PIN_CLOSE= 'PIN_CLOSE';
export const FOCUS_PIN= 'FOCUS_PIN';

//LOCATION INFO
export const SET_GOOGLE_LOCATION_INFO = 'SET_GOOGLE_LOCATION_INFO';
export const FETCH_GOOGLE_LOCATION_INFO_FAILED = 'FETCH_GOOGLE_LOCATION_INFO_FAILED';
export const LOADING_GOOGLE_DATA_DONE = 'LOADING_GOOGLE_DATA_DONE';

